services:
  inventoryservice:
    image: cppnativeexample-inventoryservice:local
    build:
      context: .
      target: inventoryservice
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        DEPENDENCY_DOCKER_REGISTRY: ${DEPENDENCY_DOCKER_REGISTRY:-docker.io}
        USERVER_LTO: ${USERVER_LTO:-ON}
        DEPENDENCY_APT_UBUNTU_ARCHIVE_URL: ${DEPENDENCY_APT_UBUNTU_ARCHIVE_URL:-}
        DEPENDENCY_APT_UBUNTU_SECURITY_URL: ${DEPENDENCY_APT_UBUNTU_SECURITY_URL:-}
        DEPENDENCY_APT_UBUNTU_PORTS_URL: ${DEPENDENCY_APT_UBUNTU_PORTS_URL:-}
        DEPENDENCY_CONAN_REMOTE_URL: ${DEPENDENCY_CONAN_REMOTE_URL:-}
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.org/simple}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST:-}
      additional_contexts:
        userver-source: ${USERVER_SOURCE_CONTEXT:-../userver}
    environment:
      NATIVE_WORKER_THREADS: ${BENCHMARK_SERVICE_CORES:-2}
      INVENTORY_SERVICE_RESPONSE_DELAY: ${INVENTORY_SERVICE_RESPONSE_DELAY:-0s}
    ports:
      - "9092:9092"
      - "9202:9202"
    networks: [app_net]

  orderservice:
    image: cppnativeexample-orderservice:local
    build:
      context: .
      target: orderservice
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        DEPENDENCY_DOCKER_REGISTRY: ${DEPENDENCY_DOCKER_REGISTRY:-docker.io}
        USERVER_LTO: ${USERVER_LTO:-ON}
        DEPENDENCY_APT_UBUNTU_ARCHIVE_URL: ${DEPENDENCY_APT_UBUNTU_ARCHIVE_URL:-}
        DEPENDENCY_APT_UBUNTU_SECURITY_URL: ${DEPENDENCY_APT_UBUNTU_SECURITY_URL:-}
        DEPENDENCY_APT_UBUNTU_PORTS_URL: ${DEPENDENCY_APT_UBUNTU_PORTS_URL:-}
        DEPENDENCY_CONAN_REMOTE_URL: ${DEPENDENCY_CONAN_REMOTE_URL:-}
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.org/simple}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST:-}
      additional_contexts:
        userver-source: ${USERVER_SOURCE_CONTEXT:-../userver}
    environment:
      NATIVE_WORKER_THREADS: ${BENCHMARK_SERVICE_CORES:-2}
      INVENTORY_SERVICE_API_CONNECTIONS_COUNT: ${INVENTORY_SERVICE_API_CONNECTIONS_COUNT:-1}
      ORDER_SERVICE_REQUEST_TIMEOUT: ${ORDER_SERVICE_REQUEST_TIMEOUT:-5s}
      ORDER_SERVICE_SOFT_DEADLINE_MARGIN: ${ORDER_SERVICE_SOFT_DEADLINE_MARGIN:-1s}
    ports:
      - "9091:9091"
    depends_on: [inventoryservice]
    networks: [app_net]

networks:
  app_net:
    driver: bridge
