components_manager:
  task_processors:
    main-task-processor:
      worker_threads: @WORKERS@
    fs-task-processor:
      worker_threads: 1
    grpc-blocking-task-processor:
      worker_threads: 1
      thread_name: grpc-worker
  default_task_processor: main-task-processor
  components:
    native-disabled-server-middlewares:
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: none
          overflow_behavior: discard
    testsuite-support:
    server:
      middleware-pipeline-builder: native-disabled-server-middlewares
      listener:
        port: 9091
        task_processor: main-task-processor
    native-status-handler:
      path: /status/data
      method: GET
      task_processor: main-task-processor
    native-metrics-handler:
      path: /metrics
      method: GET
      task_processor: main-task-processor
    grpc-client-common:
      blocking-task-processor: grpc-blocking-task-processor
    grpc-client-factory:
      disable-all-pipeline-middlewares: true
      channel-args: {}
    grpc-client-middlewares-pipeline:
    inventory-client:
      endpoint: inventoryservice:9202
      client-name: inventory
      dedicated-channel-counts:
        ProcessOrderItem: @CONNECTIONS@
      factory-component: grpc-client-factory
    handler-process-order:
      path: /v1/processorder
      method: POST
      task_processor: main-task-processor
