#!/usr/bin/env bash
set -euo pipefail

root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
userver_dir="${USERVER_SOURCE_DIR:-/opt/userver}"
build_type="${1:-Release}"
output_dir="${2:-$root/build/conan-${build_type,,}}"
profile="${CPPNATIVE_CONAN_PROFILE:-}"

if [[ ! -f "$userver_dir/conanfile.py" ]]; then
  echo "userver Conan recipe is missing: $userver_dir/conanfile.py" >&2
  exit 2
fi

if [[ -z "$profile" ]]; then
  case "$(uname -s):$(uname -m)" in
    Linux:aarch64|Linux:arm64)
      profile="$root/conan/profiles/linux-gcc-armv8"
      ;;
    Linux:x86_64)
      profile="$root/conan/profiles/linux-gcc-x86_64"
      ;;
    Darwin:arm64)
      profile="$root/conan/profiles/macos-apple-clang-armv8"
      ;;
    *)
      echo "unsupported Conan host: $(uname -s) $(uname -m)" >&2
      exit 1
      ;;
  esac
fi

version() {
  python3 "$root/conan/dependencies_generated.py" "$1"
}

effective_profile="$output_dir/cppnative-userver.profile"
mkdir -p "$output_dir"
cp "$profile" "$effective_profile"
cat "$root/conan/userver-options.generated.profile" >>"$effective_profile"
cat >>"$effective_profile" <<EOF

[replace_requires]
boost/*: boost/$(version userver-boost)
grpc/*: grpc/$(version grpc)
googleapis/*: googleapis/$(version userver-googleapis)
gtest/*: gtest/$(version userver-googletest)
librdkafka/*: librdkafka/$(version librdkafka)
opentelemetry-proto/*: opentelemetry-proto/$(version userver-opentelemetry-proto)
protobuf/*: protobuf/$(version protobuf)
re2/*: re2/$(version re2)
yaml-cpp/*: yaml-cpp/$(version yaml-cpp)

[replace_tool_requires]
protobuf/*: protobuf/$(version protobuf)
EOF

"$root/scripts/conan-configure-remotes.sh"
conan export "$root/conan/recipes/googleapis"

source_download_cache="${CPPNATIVE_CONAN_SOURCE_CACHE:-$(conan config home)/source-download-cache}"
mkdir -p "$source_download_cache"
lockfile="${CPPNATIVE_CONAN_LOCKFILE:-$root/conan/locks/$(basename "$profile").lock}"
lock_args=()
if [[ "$lockfile" != "none" ]]; then
  if [[ ! -f "$lockfile" ]]; then
    echo "Conan lockfile is missing: $lockfile; run scripts/conan-lock.sh" >&2
    exit 2
  fi
  lock_args=(--lockfile "$lockfile")
fi

conan install "$userver_dir" \
  --profile:host "$effective_profile" \
  --profile:build "$effective_profile" \
  -s:h "build_type=$build_type" \
  -s:b "build_type=$build_type" \
  -o "&:with_mongodb=False" \
  -o "&:with_postgresql=False" \
  -o "&:with_redis=False" \
  -o "&:with_clickhouse=False" \
  -o "&:with_rabbitmq=False" \
  -o "&:with_sqlite=False" \
  -o "&:with_s3api=False" \
  -o "&:with_easy=False" \
  -o "&:with_grpc=True" \
  -o "&:with_kafka=False" \
  -o "&:with_otlp=False" \
  -o "&:with_utest=False" \
  -o "&:with_grpc_reflection=False" \
  -o "&:with_grpc_protovalidate=False" \
  --build=missing \
  -cc "core.sources:download_cache=$source_download_cache" \
  -c "tools.cmake.cmaketoolchain:user_presets=" \
  "${lock_args[@]}" \
  --output-folder="$output_dir" \
  "${@:3}"

mapfile -t toolchains < <(find "$output_dir" -type f \
  -name conan_toolchain.cmake -print)
if [[ "${#toolchains[@]}" -ne 1 ]]; then
  echo "expected exactly one Conan toolchain below $output_dir, found ${#toolchains[@]}" >&2
  exit 2
fi
generator_dir="$(dirname "${toolchains[0]}")"
preset_file="$generator_dir/CMakePresets.json"
python3 - "$preset_file" "${toolchains[0]}" "conan-${build_type,,}" <<'PY'
import json
import sys

preset_path, toolchain_path, preset_name = sys.argv[1:]
with open(preset_path, encoding="utf-8") as source:
    document = json.load(source)
preset = next(
    (item for item in document.get("configurePresets", [])
     if item.get("name") == preset_name),
    None,
)
if preset is None:
    raise SystemExit(f"Conan configure preset is missing: {preset_name}")
with open(toolchain_path, "a", encoding="utf-8") as toolchain:
    toolchain.write("\n# Cache variables emitted by userver's Conan recipe.\n")
    for name, value in sorted(preset.get("cacheVariables", {}).items()):
        toolchain.write(
            f"set({name} {json.dumps(str(value))} CACHE STRING "
            '"Generated by userver Conan" FORCE)\n'
        )
PY

printf '%s\n' "${toolchains[0]}" >"$output_dir/toolchain.path"
